In [1]:
# Numpy Arrays

import numpy as np

In [21]:
# Create a Numpy array 
x = np.array([3, 2, 1])  # Pass a list
print (x)
x = np.arange(1, 7, 2)   # Use the 'arange()' function - from, to, step
print (x)
x = np.linspace(1, 7, 6) # Use the 'linspace()' function - from, to, size
print (x)
print (x.reshape(3, 2))
x = x.reshape(3, 2)      # Explicit reassignment is required
print (x)
print (x.size)           # The function 'size()' doesn't care about the shape
print (x.dtype)          # Get the storage type
print (x.itemsize)       # How much storage size (in bytes) does a single unit take up



[3 2 1]
[1 3 5]
[1.  2.2 3.4 4.6 5.8 7. ]
[[1.  2.2]
 [3.4 4.6]
 [5.8 7. ]]
[[1.  2.2]
 [3.4 4.6]
 [5.8 7. ]]
6
float64
8
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [24]:
# Create a Numpy array in multiple dimensions
x = np.array([[1, 2, 3,],
              [4, 5, 6]])  # Use multiple lists
print (x)                  
x = np.array([(1, 2, 3), 
              (4, 5, 6)]) # Group by parentheses
print (x)
x = np.arange(1, 7, 1)     
x = x.reshape(2, 3)       # Reshape a linear list
print (x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [26]:
# Mask by pass or fail criteria (binary mask)
x = np.arange(1, 37, 1)
x = x.reshape(4, 9)
print (x > 7)

[[False False False False False False False  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]]


In [28]:
# Update each element of a Numpy array 
x = np.arange(1, 37, 1)
x = x.reshape(4, 9)
print (x % 2)   # process
x %= 2
print (x)       # save changes

[[1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]]
[[1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]]


In [39]:
# Create an empty Numpy array (with zeros)
x = np.zeros(9)
print (x)
x = np.zeros((4, 9))
print (x)
try:
    x = np.zeros(4, 9)
except:
    print ("You just went from hero to zero!")
x = np.zeros((4, 9), dtype='int8')
print (x)
x = np.ones(9, dtype='int16')
print (x.dtype)
print (x.itemsize)

        

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
You just went from hero to zero!
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
int16
2


In [54]:
# Create an array with random numbers
x = np.random.random((4, 9))
print (x)
x = np.set_printoptions(precision=2, suppress=True)
print (x)
x = np.random.randint(0, 9, 7)
print (x)

[[0.67 0.41 0.61 0.32 0.64 0.97 0.43 0.73 0.73]
 [0.32 0.31 0.67 0.46 0.23 0.34 1.   0.79 0.77]
 [0.5  0.8  0.12 0.54 0.84 0.41 0.38 0.25 0.16]
 [0.18 0.82 0.93 0.96 0.41 0.82 0.19 0.31 0.21]]
None
[5 1 8 4 2 2 2]
